# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

```python
# Exercise 1
```

In [145]:
import numpy as np

a= np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

```python
# Exercise 2
```

In [147]:
x= np.zeros((3,3))
print(x)
 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

```python
# Exercise 3
```

In [148]:
s= np.linspace(0,5,10)
print (s)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.

```python
# Exercise 4
```

In [149]:
c_matrix=np.eye(5) 
print(c_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

```python
# Exercise 5
```

In [26]:
c_mat_randam = np.random.random((4,4))
print(c_mat_randam )

[[0.4832214  0.86573388 0.79226527 0.50550632]
 [0.61562838 0.60899577 0.64923813 0.94659731]
 [0.1734612  0.80318067 0.35710072 0.91649424]
 [0.95132623 0.67829401 0.31439631 0.23726487]]


---

### Exercise 6:
Find the shape of a NumPy array.

```python
# Exercise 6
```

In [28]:
np.random.seed(10)


In [32]:
a= np.random.rand(4,4)
a

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388],
       [0.49850701, 0.22479665, 0.19806286, 0.76053071],
       [0.16911084, 0.08833981, 0.68535982, 0.95339335],
       [0.00394827, 0.51219226, 0.81262096, 0.61252607]])

In [33]:
a.shape

(4, 4)

---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

```python
# Exercise 7
```

In [36]:
g= np.arange(16)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [38]:
g.reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

---

### Exercise 8:
Find the data type of the elements in a NumPy array.

```python
# Exercise 8
```

In [40]:
g.dtype

dtype('int64')

---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

```python
# Exercise 9
```

In [47]:
s= np.arange(2,101,2)
s

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

```python
# Exercise 10
```

In [55]:
a = np.random.randint(10,50,(6,6))
a


array([[17, 21, 38, 43, 30, 42],
       [34, 15, 14, 17, 34, 34],
       [44, 25, 23, 34, 25, 16],
       [31, 32, 21, 22, 38, 42],
       [25, 43, 35, 19, 47, 10],
       [28, 33, 13, 39, 26, 30]])

---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

```python
# Exercise 11
```

In [151]:
x= np.array([[1,2,3],[4,5,6]],dtype= np.int16)
y= np.array([[5,0,1],[1,15,1]],dtype= np.int16)
x-y

array([[ -4,   2,   2],
       [  3, -10,   5]], dtype=int16)

---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.

```python
# Exercise 12
```

In [152]:
x+y

array([[ 6,  2,  4],
       [ 5, 20,  7]], dtype=int16)

---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

```python
# Exercise 13
```

In [70]:
print(np.mean(x,axis=0))
print(np.mean(x,axis=1))

[2.5 3.5 4.5]
[2. 5.]


In [153]:
print( np.median(x,axis=0))
print( np.median(x,axis=1))

[2.5 3.5 4.5]
[2. 5.]


---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.

```python
# Exercise 14
```

In [154]:
print(np.max(y,axis=0))
print(np.max(y,axis=1))

[ 5 15  1]
[ 5 15]


In [73]:
print(np.min(y,axis=0))
print(np.min(y,axis=1))

[1 0 1]
[0 1]


---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

```python
# Exercise 15
```

In [156]:
m= 20
a= np.random.randint(20 ,size= m)
print(a)
print(np.argmax(a))
 

[ 7  4 14  3 15  5 15  3 14  5 14 12  2 19 18 18 14 17  6 10]
13


---

### Exercise 16:
Create a NumPy array and reverse its elements.

```python
# Exercise 16
```

In [100]:
s= np.array([[1,3,5],[1,0,4]])
print(np.flip(s)) 

[ 0  7 10 16  2  2 12 10 15  0  5 16  5 19 11 10  6  7  0  9]
[[4 0 1]
 [5 3 1]]


---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

```python
# Exercise 17
```

In [105]:
a= np.array([[1,0,1],[0,0,2],[1,1,6]])
b= np.array([[1,1,1],[2,2,2],[3,3,3]])
a*b

array([[ 1,  0,  1],
       [ 0,  0,  4],
       [ 3,  3, 18]])

---

### Exercise 18:
Create a diagonal matrix from a given 1D array.

```python
# Exercise 18
```

In [106]:
w=np.diag(a)
w

array([1, 0, 6])

---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

```python
# Exercise 19
```

In [107]:
print (np.dot(a,b))

[[ 4  4  4]
 [ 6  6  6]
 [21 21 21]]


---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

```python
# Exercise 20
```

In [109]:
print(a)
print(np.reshape(a,-1) )

[[1 0 1]
 [0 0 2]
 [1 1 6]]
[1 0 1 0 0 2 1 1 6]


---

### Exercise 21:
Stack two NumPy arrays vertically.

```python
# Exercise 21
```

In [157]:
print(x)
print(np.vstack(x))


[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


---

### Exercise 22:
Stack two NumPy arrays horizontally.

```python
# Exercise 22
```

In [121]:
print(np.hstack(x))

[1 2 3 4 5 6]


---

### Exercise 23:
Split a NumPy array into multiple sub-arrays.

```python
# Exercise 23
```

In [124]:
print (x)
print(np.split(x,2))

[[1 2 3]
 [4 5 6]]
[array([[1, 2, 3]], dtype=int16), array([[4, 5, 6]], dtype=int16)]


---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

```python
# Exercise 24
```

In [159]:
a= np.random.
#a
dtype(a)

SyntaxError: invalid syntax (1238347234.py, line 1)

---

### Exercise 25:
Find the unique elements of a NumPy array.

```python
# Exercise 25
```

In [132]:
x= np.array([1,1,4,5,3,4,3])
print(np.unique(x))

[1 3 4 5]


---

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

```python
# Exercise 26
```

In [133]:
print (x)
x[x<4]=8
print(x)

[1 1 4 5 3 4 3]
[8 8 4 5 8 4 8]


---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

```python
# Exercise 27
```

---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

```python
# Exercise 28
```

In [135]:
a= np.array([[0,1,0,4,5,0],[1,0,9,0,6,0]])
np.count_nonzero(a)

6

---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

```python
# Exercise 29
```

In [143]:
a= np.random.randint(10,20,(3,3))
print(a)


[[12 15 18]
 [11 17 11]
 [17 11 18]]


In [144]:
print (np.sort(a))

[[12 15 18]
 [11 11 17]
 [11 17 18]]


---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

```python
# Exercise 30
```

---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

```python
# Exercise 31
```

---

### Exercise 32:
Create two NumPy arrays and find the dot product.

```python
# Exercise 32
```

---

### Exercise 33:
Find the trace of a square NumPy matrix.

```python
# Exercise 33
```

---

### Exercise 34:
Create a 2D array and swap two rows.

```python
# Exercise 34
```

---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

```python
# Exercise 35
```

---

### Exercise 36:
Find the determinant of a 3x3 matrix.

```python
# Exercise 36
```

---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

```python
# Exercise 37
```

---

### Exercise 38:
Solve a system of linear equations using NumPy.

```python
# Exercise 38
```

---

### Exercise 39:
Add Gaussian noise to a NumPy array.

```python
# Exercise 39
```

---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

```python
# Exercise 40
```

---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

```python
# Exercise 41
```

---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.

```python
# Exercise 42
```

---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.

```python
# Exercise 43
```

---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.

```python
# Exercise 44
```

---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.

```python
# Exercise 45
```

---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.

```python
# Exercise 46
```

---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.

```python
# Exercise 47
```

---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.

```python
# Exercise 48
```

---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.

```python
# Exercise 49
```

---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.

```python
# Exercise 50
```

---

### Exercise 51:
Convert a NumPy array of radians to degrees.

```python
# Exercise 51
```

---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.

```python
# Exercise 52
```

---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.

```python
# Exercise 53
```

---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.

```python
# Exercise 54
```

---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

```python
# Exercise 55
```

---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.

```python
# Exercise 56
```

---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.

```python
# Exercise 57
```

---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.

```python
# Exercise 58
```

---

### Exercise 59:
Compute the Frobenius norm of a matrix.

```python
# Exercise 59
```

---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.

```python
# Exercise 60
```

---